CREATE TABLE IF NOT EXISTS staffs (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(16) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
)